### ISSUE TITLE
bad checksum OR code failure

### ISSUE THREAD

**Issue by LittlePonyta** [horrorho/InflatableDonkey#10]
Hello there,

I really appreciate the work you do. I do not want to bug you but apparently, when using this I run into a peculiar error.

```
[main] [34mINFO [0;39m c.g.horrorho.inflatabledonkey.Main - -- main() - token: Optional.empty
[main] [34mINFO [0;39m c.g.horrorho.inflatabledonkey.Main - -- main() - Account: ************************
[main] [31mWARN [0;39m c.g.h.i.data.der.KeySet - ** KeySet()  - bad checksum OR code failure
[main] [34mINFO [0;39m c.g.horrorho.inflatabledonkey.Main - -- main() - output folder backups: *:\***********************\InflatableDonkey-master\target\backups\*************************
[main] [34mINFO [0;39m c.g.horrorho.inflatabledonkey.Main - -- main() - output folder chunk cache: *:\**************************\InflatableDonkey-master\target\backups\*************************\cache
[main] [31mWARN [0;39m c.g.h.i.c.c.BackupAccountClient - -- backupAccount() - failed to retrieve protection info
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source)
        at com.github.horrorho.inflatabledonkey.BackupAssistant.backupAccount(BackupAssistant.java:89)
        at com.github.horrorho.inflatabledonkey.Backup.snapshots(Backup.java:72)
        at com.github.horrorho.inflatabledonkey.Main.main(Main.java:139)

*:\************\InflatableDonkey-master\target>
```

Just notifying you what the error is about. Again I appreciate your work and I hope by providing this we can make it a more, stable release by trying to fix it. Thanks beforehand.

**Comment by manwhoami** [comment]
Are you sure that account has a backup for iOS 9+?

**Comment by horrorho** [comment]
Thank you for the ticket, and no you're not bugging me.

As @manwhoami has suggested are you certain that it's an iOS9 backup? You could give (LiquidDonkey)[https://github.com/horrorho/LiquidDonkey] a go for iOS8 backups.

Either way, at some point I should really tidy up InflatableDonkey's handling of non-iOS9 accounts. It doesn't expect iOS8 accounts and doesn't really know what to do with them other than throw errors.

**Comment by LittlePonyta** [comment]
I see. And yes it does contain a backup but I haven't checked if it is IOS9 or IOS8. Thanks for the notification, but how can I see which kind of backup it is? Thanks beforehand.

**Comment by horrorho** [comment]
I'm not an iOS/ O SX user so I couldn't tell you the best way to check from that perspective. I'd suggest either giving (iLoot)[https://github.com/hackappcom/iloot] or (LiquidDonkey)[https://github.com/horrorho/LiquidDonkey]  a go, they'll pick up any iOS8 backups.

**Comment by horrorho** [comment]
Ok. I've introduced new error code that will explicitly warn about the lack of iOS9 backups as opposed to the previous cryptic output. Hopefully this will clear up any confusion and assist users.
