### ISSUE TITLE
icloud Ask questions

### ISSUE THREAD

**Issue by cyanBone** [horrorho/InflatableDonkey#103]
Hello:

X-Apple-I-MD-M:
X-Apple-I-MD-RINFO:
X-Apple-I-MD:

How are these things obtained?

Mac os icloud

**Comment by RobLinux** [comment]
by the magic of R&D. Do you even search if your question has been asked in other threads ?

**Comment by cyanBone** [comment]
X-MMe-Nas-Session 
 How are these things obtained? Mac os icloud
@RobLinux

**Comment by RobLinux** [comment]
🤷

**Comment by cyanBone** [comment]
thinks

**Comment by cyanBone** [comment]
thanks
