### ISSUE TITLE
Exception at BackupAssistant.java immediately after running

### ISSUE THREAD

**Issue by febul** [horrorho/InflatableDonkey#11]
This is what I get immediately after I run the utility with a username + password, when it tries to load the snapshots.

> [main] WARN  c.g.h.i.c.c.BackupAccountClient - -- backupAccount() - failed to retrieve protection info
> Exception in thread "main" java.util.NoSuchElementException: No value present
> 	at java.util.Optional.get(Optional.java:135)
> 	at com.github.horrorho.inflatabledonkey.BackupAssistant.backupAccount(BackupAssistant.java:89)
>

**Comment by t3zuka** [comment]
See issue #10

**Comment by horrorho** [comment]
Thank you for the report and yes @t3zuka beat me to it. I will code in a more appropriate error, I'm just working on other more pressing issues at present.

**Comment by horrorho** [comment]
Duplicate #10
