### ISSUE TITLE
Unreadable files from AppDomainGroup-group.com.kik.chat

### ISSUE THREAD

**Issue by colincowie10** [horrorho/InflatableDonkey#12]
Hello, 

I recently tried the new build on my icloud that was having issues previously with opening some app domain files, such as attachments, .plist files and more. Initially it chose CBC, the files were still unreadable, then I tried --mode XTS and they were still unreadable. Thank you for the hard word

Example with --mode XTS
`18:14:34.939 [main] INFO  c.g.h.i.file.FileAssembler - -- write() - written: backups/APPLEID/DEVICEHASH/20160717/AppDomainGroup-group.com.kik.chat/cores/private/75f5929ef6674491bffeb2f92d2e5b69/attachments/f23397a6-a80a-4671-9d45-bdff118f3868 status: true mode: AES_XTS flags: 0x0000000000bf4f0e01000001
`
Example without --mode XTS
`18:29:37.509 [main] INFO  c.g.h.i.file.FileAssembler - -- write() - written: backups/APPLEID/DEVICEHASH/AppDomainGroup-group.com.kik.chat/cores/private/75f5929ef6674491bffeb2f92d2e5b69/attachments/afbb82ff-51ff-4af2-9530-e7e82327f479 status: true mode: AES_CBC flags: 0x0000000000bf37f701000001
`

**Comment by horrorho** [comment]
Hi. Are you able to open images in the MediaDomain folder with either CBC or XTS?

**Comment by colincowie10** [comment]
Yes

**Comment by horrorho** [comment]
Ok. If you can view images in the MediaDomain then Data Protection decryption appears to be working. It's probably an additional encryption layer by Kik, though obviously I could be wrong.

I'll try and test Kik. As I don't own an iPhone, I'll need to clobber a friend to install it and let me play with it.

**Comment by horrorho** [comment]
Ok, I can't convince anyone to install Kik. The examples you've linked have hash based file names and no extension suffix. As other files are decrypting I suspect they have also decrypted, just not into a format you're able to use.

Closing this issue.

**Comment by horrorho** [comment]
Ok! I finally managed to test on Kik.

AppDomainGroup-group.com.kik.chat files are being retrieved just fine.

The files you referenced earlier in AppDomainGroup-group.com.kik.chat/cores/private are bplist files. I can pull images out of them manually using a hex editor. It should be possible to create a tool for them, but I probably won't be writing one.

Consider something like [Oxygen Forensics](http://www.oxygen-forensic.com)
