### ISSUE TITLE
Snapshot selection

### ISSUE THREAD

**Issue by Aliasr** [horrorho/InflatableDonkey#13]
It seems to me that the couple last versions ignore the snapshot flag. I already tried using 1, 2 and -1 as arguments. Can someone else confirm this please? Also thanks @horrorho for the awesome job.

**Comment by rodrimc** [comment]
I've noticed this same issue.

**Comment by horrorho** [comment]
Thank you for the ticket. I'm currently porting over some of [LiquidDonkey's](https://github.com/horrorho/LiquidDonkey) command line argument methods and re-factoring other code. So this issue should hopefully be resolved by the end of the weekend.

**Comment by maluba007** [comment]
Merge pull request #15 from mattandersen/master resolved this issue for snapshots, but not for devices

**Comment by mattandersen** [comment]
Device filtering works just fine. You have to specify the device's UUID, displayed to the left of the model number when listing snapshots.

Example:
`java -jar InflatableDonkey.jar <username> <password> -d 1234567890ABCDF1234567890ABCDF1234567890 -s 2 --extension sms.db`

That would download the Messages database from the 2nd snapshot of device  1234567890ABCDF1234567890ABCDF1234567890

**Comment by topada** [comment]
Awesome! I misread the readme and was going for --device 1 

Thanks!
