### ISSUE TITLE
code conversion to c++

### ISSUE THREAD

**Issue by prateek1108** [horrorho/InflatableDonkey#14]
Hi,

I had tried this code in java a excellent job is done for downloading ios backup. i want this code in c++ or vc++ or python because of dependency on java installation and framework to run this code. Can i run or make .exe of this code and run as a standalone executable without java dependency.

**Comment by horrorho** [comment]
Hi there. There are Java AOT compilers out there, but I have no experience with them. I'm afraid I can't offer you any solid advice on the issue.

**Comment by prateek1108** [comment]
thanks for your guidance i successfully created standalone setup by "Excelsior". But i am facing a small problem the setup size is too large. can i remove few file from this project and then i can build the code. i only need icloud support.

**Comment by horrorho** [comment]
I've only put in the bare bones of what need for iCloud backups, I'm not sure we can really cut anything out with breaking it.

**Comment by horrorho** [comment]
As an afterthought: most of the code base will be in the additional libraries we use, much of which is extra baggage. I had a quick google to see what can be done to remove them and solutions like [ProGuard](http://proguard.sourceforge.net/) are mentioned. Again I have no experience with this, but it's a possible avenue you might want to explore.

**Comment by horrorho** [comment]
Closing issue, please reopen if you have any further questions.
