### ISSUE TITLE
features: multiple filter, high-level filter, skip files, flat output

### ISSUE THREAD

**Issue by maluba007** [horrorho/InflatableDonkey#17]
horrorho! First of all: where is that piggy bank of yours we can flood with love and gratefulness? this is an amazing project and i'm impressed by your persistence!

here are a couple of my feature ideas (rather low priority!)

- Filter multiple extensions at once like "--extension jpg,jpeg"
- Filter extensions on a higher abstraction level like "--extensions photos videos"
- Skip existing files
- optional flat output folder structure /output/file.ext  vs. /device/snapshot/domain/d1/d2/file.ext

most respectfully –
a vampire in the darkness :)

**Comment by horrorho** [comment]
Hi! Thanks for the feedback.

1. Use extension without spaces to pass multiple values: --extension jpg jpeg. I'll update the --help to clarify this.
2. Is on the to do list.
3. Chunk data is cached. So files are re-constructed without the need to down the chunk data again. I've yet to reverse Data Protection checksums (I hate reversing code) so we just re-construct the file as we can't verify it's integrity.
4. I'm holding off manipulating backups after retrieval as there are endless combinations that users might want. It's simpler to use your OS file manager or shell scripts to get the job done. The only option I do want is an iTunes style backup format as we have in iLoot.

**Comment by onehit** [comment]
horrorho,

Thanks for your work on this.
I'm getting an error when specifying a snapshot - it's copying to the temp directory but is not creating the correct folders in the cache directory so it is unable to copy them.

[ForkJoinPool-1-worker-1] [31mWARN [0;39m c.g.h.i.c.store.disk.DiskChunkStore - -- copy() - failed to write to temporary file: backups\xxxxxxxxxxx\temp\xxxxxxxxxxx.tmp chunk: backups\xxxxxxxxxxx\cache\8\1\4\xxxxxxxxxxx

[ForkJoinPool-1-worker-1] [31mWARN [0;39m c.g.h.i.c.engine.ChunkListDecrypters - -- copy() - failed to copy chunk data: xxxxxxxxxxx ex: {}

java.nio.file.NoSuchFileException: backups\xxxxxxxxxxx\temp\xxxxxxxxxxx.tmp -> backups\xxxxxxxxxxx\cache\8\1\4\xxxxxxxxxxx

**Comment by horrorho** [comment]
Thank you for the feedback and sorry! I stuffed up there quite badly. You've hit the nail on the head and I've already updated the working tree.

As you may have guessed, I was testing on a cached backup so I missed the bug.

**Comment by horrorho** [comment]
Issue resolve. Closing ticket!
