### ISSUE TITLE
Can't read plist file

### ISSUE THREAD

**Issue by satashi2009** [horrorho/InflatableDonkey#2]
Hi,
This is great tool, but I have a problem.
I can't read plist file download from any domain.
it is in binary plist format, but can't open and can't convert to xml format.
do you know why ?

**Comment by njonjo1985** [comment]
If it is a binary plist, you should be able to convert it by opening up a Terminal and running "plutil -convert xml1 file.plist" (no quotes). Needs to be on OS X

**Comment by satashi2009** [comment]
Thank you,
Here is error when convert with plutil: `Property List error: Unexpected character b at line 1 / JSON error: JSON text did not start with array or object and option to allow fragments not set.`
I delete them and download again, same problem (eg domain: AppDomain-com.skype.skype)

**Comment by horrorho** [comment]
Sorry the delay. I've pushed a new build that you may like to test. Please advise if the issue persists.

**Comment by satashi2009** [comment]
wow. worked well. thank you

**Comment by horrorho** [comment]
Thank you for the feedback! I'll go ahead and close this ticket.
