### ISSUE TITLE
Only .tmp files

### ISSUE THREAD

**Issue by Egospastic** [horrorho/InflatableDonkey#20]
I think I'm missing something here. Every time I've downloaded a backup, I only get the "temp" folder and nothing else. Just that folder filled with tmp files. Am I meant to decrypt them myself or is there something faulty with my setup? I should probably specify I've only tried this with media files thus far.

**Comment by horrorho** [comment]
Please try and older build https://github.com/horrorho/InflatableDonkey/archive/34643ea84d077d1341c50d59a6cd1233b8455ddb.zip.

I'll update the working tree as soon as I can. Sorry for the inconvenience.

**Comment by maluba007** [comment]
unfortunately, same here even with the linked build – just temp files with following error:

`[ForkJoinPool-1-worker-1] WARN  c.g.h.i.cloud.AssetDownloader - -- assembleFileChunkList() - missing chunks: Asset{assetID=F:XXXXXXX-ED13-4713-9C67-F8E6558DF2A7:JnARUcVBoIb0cho9MAOgGsLWjYM=:10084:a9shprotectionClass=Optional.empty, size=Optional[10084], fileType=Optional[0], downloadTokenExpiration=Optional[2016-07-28T22:45:00Z], contentBaseURL=Optional[https://p35-content.icloud.com:443], fileChecksum=Optional[01ceffc32dcb9898ebd86c4a92706f31d9449b4d30], fileSignature=Optional[01c47fee9ee22fdfb2714b0e214c032f72f38a8f21], keyEncryptionKey=Optional[f4435c29058a7fbfca422ffd47897d33], encryptedAttributes=Optional[<?xml version="1.0" encoding="UTF-8"?>`

**Comment by Egospastic** [comment]
Yeah, seems to be the same for me as well.

**Comment by maluba007** [comment]
@horrorho i want to marry your brain!

**Comment by horrorho** [comment]
Is the issue still present on the latest build? I may have stuffed up the filtering somewhere. Also are we passing in any filtering parameters?

**Comment by maluba007** [comment]
latest build resolved the issue perfectly! everything working with parameters aswell 👍

**Comment by horrorho** [comment]
Ok, thank you for putting my mind at rest!

I'll close the ticket for now, please let me know if you have any further issues.
