### ISSUE TITLE
Feature: Including the photostream?

### ISSUE THREAD

**Issue by maluba007** [horrorho/InflatableDonkey#23]
horrorho sensei et all,
I noticed reincubate's iphone backup extractor gives you access to your photostream, which doesn't seem to be a part of the general backups. I deactivated my icloud backups (InflateableDonkey returns No Snapshots/No Devices), still with reincubate i can download my photostream data. anyone familiar with the icloud/photostream connections?

**Comment by horrorho** [comment]
Hi, Photo Stream operates via different mechanics. It's much easier to work with than Cloud Kit. I did write a retrieval tool years ago for it though I'm not sure if it still works. However I barely have enough time to devote to this project, so I'm not going to touch it.
