### ISSUE TITLE
Directories Within a Domain

### ISSUE THREAD

**Issue by test12ing34** [horrorho/InflatableDonkey#26]
Is it possible to download less than an entire domain? For instance, instead of downloading the entire HomeDomain, is there a way to simply download the Notes folder from the HomeDomain?

Any help with this matter would be greatly appreciated.

**Comment by horrorho** [comment]
Hi there. In addition to the --domain option use the --relative-path option with the folder/s you would like to retrieve.

```
--domain homedomain --relative-path notes
```

**Comment by manwhoami** [comment]
To add to that, if you want to download a file that you know the name of, you can send it in as part of the --extension argument.

I.E., you want the notes.sqlite database file (contains all of the notes in iOS backup), run InflatableDonkey with --extension='notes.sqlite'. ID treats "notes.sqlite" as an extension to look for. 

@horrorho this makes me wonder, would it be possible / difficult to implement regular expressions into the current domain / relative path / extension arguments? To allow for even more selective downloading? (Example, any .jpg files that start with IMG and have anything in between). I am not sure of standard regex libraries in Java. I know in python this would be a relatively easy task.

**Comment by horrorho** [comment]
@manwhoami it is possible to implement regex searches, although there will be subtle variations in syntax to Python. I actually did consider it, but I didn't think many users would use them and I also have other features I would like to implement first.
