### ISSUE TITLE
Snapshots download process question

### ISSUE THREAD

**Issue by ajlyakhov** [horrorho/InflatableDonkey#28]
Could you please explain, why InflatableDonkey retrieve data from previous snapshots while I need filed from specified one? For example, I have 3 snapshots (initial, second and third). I've not completely downloaded initial (it is 19G size) and want to download only third (100M). When I said to retrieve it with "--snapshot 2" I see that it is downloading files from initial snapshot. Just trying to understand the logic behind that. I'm thinking about workflow like this:

1) user specify date range to get some data type (for example, call logs)
2) execute "script" and expect to receive only logs from specified time range

Would that **require** script to retrieve all previous backups history to get data from specified date range or not?

**Comment by horrorho** [comment]
Hi there. Snapshots are incremental backups. If a file as been altered then it may appear across all snapshots its different forms. So for example things like the call history or the sms db are often present in all three backups.

However! There are some subtle bugs in the filtering mechanism and a missing optimisation that was present in [LiquidDonkey](https://github.com/horrorho/LiquidDonkey) that disregarded irrelevant backups when specifying a date range. At present InflatableDonkey will download and trawl through the file manifest for every snapshot, even if the snapshot is too old to satisfy the date filter constraints.

So the answer to your question is no, we don't need to download backups prior to your date range. It's sub-optimal behaviour which I'll fix. There are additional optimisations that are also missing.

I'll try and get the code fixes out by the weekend. I'm half way through reworking the concurrent download engine to auto-tune and handle small files efficiently, so if there are issues with that then it may get delayed.

**Comment by horrorho** [comment]
Closing. Should be fixed in the latest build.
