### ISSUE TITLE
Blank image/video files

### ISSUE THREAD

**Issue by Egospastic** [horrorho/InflatableDonkey#31]
I've been having a problem with backups being downloaded with blank image and video files. The files are the sizes they should be but there's nothing on them if that makes sense. It's only with some downloads though, I don't know if it's an issue with the backup or the program but help would be appreciated.

Thank you!

**Comment by horrorho** [comment]
Hi. By blank, I'm assuming they are corrupted random data as opposed to a file full of zeros. You can confirm this using any hex editor.

If they are corrupted as opposed to being blank. Then you can try downloading with --mode CBC and if that fails with --mode XTS.

If you're still having issues, then let me know which application/ domain the files belong to.

**Comment by horrorho** [comment]
No response. Closing. Possible duplicate of https://github.com/horrorho/InflatableDonkey/issues/18.
