### ISSUE TITLE
Error while debugging in eclipse

### ISSUE THREAD

**Issue by prateek1108** [horrorho/InflatableDonkey#34]
Hi,

I had tried to debug the code in Eclipse LUNA. and also installed maven as plugin in eclipses. few error are there at run-time. Please help me out to resolve these errors. 

Description	Resource	Path	Location	Type
The method map(Function<? super Object,? extends R>) in the type Stream<Object> is not applicable for the arguments (KeyBagID::new)	KeyBagManager.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 109	Java Problem

The type KeyBagID does not define KeyBagID(Object) that is applicable here	KeyBagManager.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 109	Java Problem

The type Map.Entry does not define getKey(Object) that is applicable here	BackupAssistant.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 117	Java Problem

The type Map.Entry does not define getValue(Object) that is applicable here	BackupAssistant.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 117	Java Problem

The type of uuid(byte[]) from the type KeyBlob is Optional<byte[]>, this is incompatible with the descriptor's return type: Optional<Object>	KeyBagManager.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 106	Java Problem

The type of uuid(byte[]) from the type KeyBlob is Optional<byte[]>, this is incompatible with the descriptor's return type: Optional<Object>	KeyBagManager.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 106	Java Problem

Type mismatch: cannot convert from Map<Object,Object> to Map<SnapshotID,Device>	BackupAssistant.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey	line 110	Java Problem

The type Map.Entry does not define getKey(Object) that is applicable here	BiMapSet.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey/util	line 59	Java Problem

The type Map.Entry does not define getKey(Object) that is applicable here	BiMapSet.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey/util	line 66	Java Problem

The type Map.Entry does not define getValue(Object) that is applicable here	BiMapSet.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey/util	line 59	Java Problem

The type Map.Entry does not define getValue(Object) that is applicable here	BiMapSet.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey/util	line 66	Java Problem

Type mismatch: cannot convert from Map<Object,Set<Object>> to Map<K,Set<V>>	BiMapSet.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey/util	line 54	Java Problem

Type mismatch: cannot convert from Map<Object,Set<Object>> to Map<V,Set<K>>	BiMapSet.java	/InflatableDonkey/src/main/java/com/github/horrorho/inflatabledonkey/util	line 61	Java Problem

**Comment by horrorho** [comment]
Hi. I have little experience with Eclipse, I use NetBeans. For some reason your debugger is having issues with some Java 8 code/ generics. Are you using the latest versions of JDK/ Eclipse/ plugins?

If you could let me know the result of issuing this command:
```
javac -version
```

**Comment by horrorho** [comment]
Hi. I have little experience with Eclipse, I use NetBeans. For some reason your debugger is having issues with some Java 8 code/ generic types. Are you using the latest versions of JDK/ Eclipse/ plugins?

If you could let me know the result of issuing this command:
```
javac -version
```

**Comment by horrorho** [comment]
Ok. I can build/ test the project using [Eclipse](https://eclipse.org/) Neon without issue and without additional plugins. Luna is two years old. There have been two Eclipse releases since.

**Comment by prateek1108** [comment]
javac -version
1.8.0.0_91

i am also upgrading my java and eclipse version then i again  build/ test the project

**Comment by horrorho** [comment]
Your JDK is also out of date. That's probably all the help I can offer. You'll need to find someone who knows how to use Eclipse.

**Comment by prateek1108** [comment]
hello sir,
I had updated jdk and eclipse version now the code is running fine in eclipse. Thanks alot for your help...

**Comment by horrorho** [comment]
Excellent and thank you for the feed back. Happy debugging!
