### ISSUE TITLE
Bad Apple ID

### ISSUE THREAD

**Issue by nothanktee** [horrorho/InflatableDonkey#39]
Im using an apple ID that keeps returning as bad apple id/not an icloud account

I know the phone is using iOS 10 but part of me thinks the issue is the fact the password has a $ in it, is there any way to get around this?

**Comment by horrorho** [comment]
Hi. Have you tried enclosing the password in quotes?
```
java -jar InflatableDonkey.jar appleid@icloud.com 'password$'
```

**Comment by nothanktee** [comment]
It worked perfect! Thank you :)

**Comment by horrorho** [comment]
Excellent. Thank you for the quick feedback.

**Comment by horrorho** [comment]
Closing issue.
