### ISSUE TITLE
failed to fetch key bag

### ISSUE THREAD

**Issue by asifmehmoood** [horrorho/InflatableDonkey#40]
Hi,
 Thank you for your excellent work done. I have an bug that occurs when downloading Backup. 
 iOS 9.3.2

 I try to download with other library i.e ricloud and its work fine.

 sample out put looks like.
 KeyBagClient - -- keyBag() - keybag UUID: K:fSpKrgFWR0+pTYQVorjAkA==
KeyBagManager - -- keyBagClient() - IOException: com.github.horrorho.inflatabledonkey.exception.BadDataException KeyBagFactory, no key bag data
KeyBagManager -  --fetchKeyBag() - failed to fetch key bag: K:fSpKrgFWR0+pTYQVorjAkA==
KeyBlobCurve25519Unwrap - -- doUnwrap() - no public key for protection class: 3
FileAssembler - -- decrypt() - failed to unwrap encryption key

Thank you for the help and your hard work on this project.

**Comment by horrorho** [comment]
Duplicate #36.

**Comment by horrorho** [comment]
This has been reported previously. In that case other tools also had issues with the recovery process. The presumption was that the backup itself was probably faulty.

Are you able to test the backup by restoring it successfully to a device or by using another iCloud recovery tool?
