### ISSUE TITLE
some backups dont work

### ISSUE THREAD

**Issue by nirlandau** [horrorho/InflatableDonkey#42]
Hi
I ran the InflatableDonkey many times and until now everything worked great.

Today I tried to download a new backup (different user, different phone-iPhone 4, iOS 7.1.2) and I keep getting this output:

![image](https://cloud.githubusercontent.com/assets/10527698/20134170/20f0beb0-a673-11e6-8d41-c375c698a97c.png)

What maybe the reason?
Same result with username/password or token.

Thanks
Nir

**Comment by horrorho** [comment]
Hi. InflatableDonkey is iOS 9+. Try [iLoot](https://github.com/hackappcom/iloot/) for iOS 8 and earlier backups.

**Comment by nirlandau** [comment]
i'll try that
thank you very much

**Comment by horrorho** [comment]
I have been meaning to intercept this error and produce a more meaningful error statement.
