### ISSUE TITLE
Reg: Help needed for filtering downloads

### ISSUE THREAD

**Issue by rameshT108** [horrorho/InflatableDonkey#45]
Hello,

Will you please give me a sample to download only HomeDomain folder and i need a Photos also..
Your help most appreciatable.

**Comment by horrorho** [comment]
Hi. Paths are constructed as: domain / relative-path
The tail characters of the relative-path are considered to be the file extension.

If we take the file: CameraRollDomain/Media/DCIM/101APPLE/IMG_1000.JPG
domain =  CameraRollDomain
relative-path = Media/DCIM/101APPLE/IMG_1000.JPG
extension = JPG, .JPG, 0.JPG etc.

Just apply the case-insensitive filters as required.

To download all files from HomeDomain:
```Java
java -jar InflatableDonkey.jar AUTH --domain homedomain
```
To download all photos from all domains:
```Java
java -jar InflatableDonkey.jar AUTH --extension .jpg .jpeg
```
or
```Java
java -jar InflatableDonkey.jar AUTH --item-type PHOTOS
```
Further example, to download all photos ending with 0.jpg from the camera roll after 31st Jan 2016
```
java -jar InflatableDonkey.jar AUTH --domain camerarolldomain --extension 0.jpg --date-min 2016.1.31
```
AUTH is either your AppledID and password or dsPrsID:mmeAuthToken.

**Comment by rameshT108** [comment]
Thanks for the reply, 
You have a done fab job . I have some Images in cloud Photos but i didn't getting any pics . Please help me

**Comment by horrorho** [comment]
There are hacked versions of InflatableDonkey that download iCloud iOS9+ photos but I won't be releasing them at this time. Sorry.

**Comment by rameshT108** [comment]
Hello,
I'm getting while integrating with Spring webmvc project all the classes are there the following error occurring while performing download operation. It will not work with Spring?

java.lang.NoClassDefFoundError: Could not initialize class com.icloudifd.horrorho.inflatabledonkey.protobuf.CloudKit

**Comment by horrorho** [comment]
I've not played around with Spring so I can't offer any assistance. Sorry.

**Comment by rameshT108** [comment]
java -jar InflatableDonkey.jar someId;sometojen --domain homedomain --extension callhistorydb

is it correct to retrieve only call history?

**Comment by horrorho** [comment]
@rameshT108 CallHistoryDB is a folder, not an extension.

iOS9
```
java -jar InflatableDonkey.jar AUTH --domain homedomain --relative-path callhistorydb
```
or
```
java -jar InflatableDonkey.jar AUTH --item-type CALL_HISTORY
```

iOS10 see https://github.com/horrorho/InflatableDonkey/issues/37

**Comment by rameshT108** [comment]
Hello,
Can we filter two different domains with relative path also like
java -jar InflatableDonkey.jar AUTH --domain whatsapp homedomain --relative-path sms

**Comment by horrorho** [comment]
Hi. Not in the way I think you would like. The filters tag onto each other. They are pretty much in the style of iLoot with additional options.
```
java -jar InflatableDonkey.jar AUTH --domain whatsapp homedomain --relative-path sms
```
With this, the domain needs to be either contain the string whatsapp or homedomain AND the relative path must contain sms. Unless your WhatsApp domain contains an sms folder it will not download anything from WhatsApp.

If you let me know the files that you would like to retrieve from WhatsApp and SMS, I might be able to assist further in crafting a query.

**Comment by rameshT108** [comment]
Hello Thanks for the reply,
Actually, i want some folders from home domain for example SMS/ Address book and I want other applications folders also example facebook / WhatsApp. then how can I filter these? or else I need to run process separately for two of them?

**Comment by horrorho** [comment]
No further discussion, closing issue.
