### ISSUE TITLE
What is Unique ID for device coming while choose the device snapshot

### ISSUE THREAD

**Issue by wiswashegrove** [horrorho/InflatableDonkey#47]
Hi There,
It may confuse you.
I want to know what is the snapshot id `18AFF02F6FD2DE96A173C8B018A42D675ABDCCDE`
Its not device unique id.

My objective is I want to get co-relate pyicloudService(https://github.com/picklepete/pyicloud) id with the above which is coming like:

`{
u'i9vbKRGIcLYqJnXMd1b257kUWnoyEBcEh6yM+IfmiMLh7BmOpALS+w==': <AppleDevice(iPhone 4S: Johnny Appleseed's iPhone)>
}`

I am not a Java guy, trying to use it. Need your assistance to understand the problem.

Thanks in advance

**Comment by horrorho** [comment]
Hi there. I understand the general direction in which you want to go, but I need more accurate information.

It's not clear to me how you arrived at the snapshot id:
'18AFF02F6FD2DE96A173C8B018A42D675ABDCCDE'.

If you would kindly clarify this. It sounds like you're actually referencing a backup device id.

Run InflatableDonkey and let me know the DEVICE ids for all of your devices and their names. It will print this information out at the selection prompt.

Run pyicloud and let me know the output of the api.devices property.

There are additional fields such as UniqueDeviceID/ SerialNumber which are not exposed at present. To examine these if you alter this [file at line 62](https://github.com/horrorho/InflatableDonkey/blob/master/src/main/java/com/github/horrorho/inflatabledonkey/data/backup/SnapshotFactory.java#L62)
```Java
            logger.info("-- from() - snapshot: {}", snapshot);
```
to
```Java
            logger.error("-- from() - snapshot: {}", snapshot);
```
Recompile and run. This will dump out details of the snapshot as an error. If you would kindly let me know what the UniqueDeviceID value is.

**Comment by wiswashegrove** [comment]
Hello,
Thank you very much for your response.

Here I am pasting the data you want to see.

PyIcloud 
```
>>>api.devices
{u'JZjgKSFsEPaYjx5LtKIuAB2wZzr91Xk7V5iQyuyzmyepispN6V8xd+HYVNSUzmWV': <AppleDevice(iPad Air 2: Suhail 's iPad)>}

# that device details report
>>>api.devices['JZjgKSFsEPaYjx5LtKIuAB2wZzr91Xk7V5iQyuyzmyepispN6V8xd+HYVNSUzmWV'].content
{u'activationLocked': True,
 u'batteryLevel': 0.0,
 u'batteryStatus': u'Unknown',
 u'canWipeAfterLock': True,
 u'darkWake': False,
 u'deviceClass': u'iPad',
 u'deviceColor': u'3b3b3c-b4b5b9',
 u'deviceDisplayName': u'iPad Air 2',
 u'deviceModel': u'SixtheGen-4G-3b3b3c-b4b5b9',
 u'deviceStatus': u'203',
 u'features': {u'CLK': False,
  u'CLT': False,
  u'CWP': False,
  u'KEY': True,
  u'KPD': True,
  u'LCK': True,
  u'LKL': True,
  u'LKM': False,
  u'LLC': False,
  u'LMG': False,
  u'LOC': True,
  u'LST': True,
  u'MSG': True,
  u'PIN': False,
  u'REM': False,
  u'SND': True,
  u'SVP': False,
  u'TEU': True,
  u'WIP': True,
  u'WMG': True,
  u'XRM': False},
 u'fmlyShare': False,
 u'id': u'JZjgKSFsEPaYjx5LtKIuAB2wZzr91Xk7V5iQyuyzmyepispN6V8xd+HYVNSUzmWV',
 u'isLocating': True,
 u'isMac': False,
 u'locFoundEnabled': False,
 u'location': None,
 u'locationCapable': True,
 u'locationEnabled': True,
 u'lockedTimestamp': None,
 u'lostDevice': None,
 u'lostModeCapable': True,
 u'lostModeEnabled': False,
 u'lostTimestamp': u'',
 u'lowPowerMode': False,
 u'maxMsgChar': 160,
 u'mesg': {u'createTimestamp': 1481615313850L, u'statusCode': u'205'},
 u'modelDisplayName': u'iPad',
 u'msg': {u'createTimestamp': 1481615313850L,
  u'playSound': False,
  u'statusCode': u'205',
  u'strobe': False,
  u'userText': True,
  u'vibrate': False},
 u'name': u"Suhail 's iPad",
 u'passcodeLength': 6,
 u'prsId': None,
 u'rawDeviceModel': u'iPad5,4',
 u'remoteLock': None,
 u'remoteWipe': None,
 u'snd': None,
 u'thisDevice': False,
 u'trackingInfo': None,
 u'wipeInProgress': False,
 u'wipedTimestamp': None}
```


Response come from InflatableDonkey is as below
```

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
13:38:30.222 [main] [1;31mERROR[0;39m c.g.h.i.data.backup.SnapshotFactory - -- from() - snapshot: Snapshot{snapshotID=S:B1CC4567-FD9F-4435-ABAE-792303BBEFC4, backupProperties=Optional[<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Version</key>
	<string>9.1</string>
	<key>Date</key>
	<date>2016-08-24T07:15:20Z</date>
	<key>SystemDomainsVersion</key>
	<string>24.0</string>
	<key>WasPasscodeSet</key>
	<false/>
	<key>AppleIDs</key>
	<dict>
		<key>tab@hasbroclothing.com</key>
		<dict>
		</dict>
		<key>prince18raj@gmail.com</key>
		<dict>
		</dict>
	</dict>
	<key>ActiveAppleID</key>
	<string>tab@hasbroclothing.com</string>
	<key>Lockdown</key>
	<dict>
		<key>com.apple.MobileDeviceCrashCopy</key>
		<dict>
		</dict>
		<key>com.apple.TerminalFlashr</key>
		<dict>
		</dict>
		<key>com.apple.mobile.data_sync</key>
		<dict>
			<key>Contacts</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Calendars</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Bookmarks</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Notes</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
		</dict>
		<key>com.apple.Accessibility</key>
		<dict>
			<key>SpeakAutoCorrectionsEnabledByiTunes</key>
			<false/>
			<key>ZoomTouchEnabledByiTunes</key>
			<false/>
			<key>InvertDisplayEnabledByiTunes</key>
			<false/>
			<key>ClosedCaptioningEnabledByiTunes</key>
			<false/>
			<key>MonoAudioEnabledByiTunes</key>
			<false/>
			<key>VoiceOverTouchEnabledByiTunes</key>
			<false/>
		</dict>
		<key>ProductVersion</key>
		<string>9.3.2</string>
		<key>ProductType</key>
		<string>iPad5,4</string>
		<key>BuildVersion</key>
		<string>13F69</string>
		<key>com.apple.mobile.iTunes.accessories</key>
		<dict>
		</dict>
		<key>com.apple.mobile.wireless_lockdown</key>
		<dict>
		</dict>
		<key>UniqueDeviceID</key>
		<string>cb2f24e654d6d32223d9c96d9ee1115dca2a5b1e</string>
		<key>SerialNumber</key>
		<string>DMPR8D6MG5WQ</string>
		<key>DeviceName</key>
		<string>Suhail 's iPad</string>
	</dict>
	<key>SnapshotHMACKey</key>
	<data>
		+/3Lrnx9JoB2Rrz3GNa2wGM8iQU=
	</data>
</dict>
</plist>]}
13:38:30.235 [main] [1;31mERROR[0;39m c.g.h.i.data.backup.SnapshotFactory - -- from() - snapshot: Snapshot{snapshotID=S:A70A1F39-AE08-440B-9F05-8C24EB497056, backupProperties=Optional[<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Version</key>
	<string>9.1</string>
	<key>Date</key>
	<date>2016-08-27T07:21:18Z</date>
	<key>SystemDomainsVersion</key>
	<string>24.0</string>
	<key>WasPasscodeSet</key>
	<false/>
	<key>AppleIDs</key>
	<dict>
		<key>tab@hasbroclothing.com</key>
		<dict>
		</dict>
		<key>prince18raj@gmail.com</key>
		<dict>
		</dict>
	</dict>
	<key>ActiveAppleID</key>
	<string>tab@hasbroclothing.com</string>
	<key>Lockdown</key>
	<dict>
		<key>com.apple.MobileDeviceCrashCopy</key>
		<dict>
		</dict>
		<key>com.apple.TerminalFlashr</key>
		<dict>
		</dict>
		<key>com.apple.mobile.data_sync</key>
		<dict>
			<key>Contacts</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Calendars</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Bookmarks</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Notes</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
		</dict>
		<key>com.apple.Accessibility</key>
		<dict>
			<key>SpeakAutoCorrectionsEnabledByiTunes</key>
			<false/>
			<key>ZoomTouchEnabledByiTunes</key>
			<false/>
			<key>InvertDisplayEnabledByiTunes</key>
			<false/>
			<key>ClosedCaptioningEnabledByiTunes</key>
			<false/>
			<key>MonoAudioEnabledByiTunes</key>
			<false/>
			<key>VoiceOverTouchEnabledByiTunes</key>
			<false/>
		</dict>
		<key>ProductVersion</key>
		<string>9.3.2</string>
		<key>ProductType</key>
		<string>iPad5,4</string>
		<key>BuildVersion</key>
		<string>13F69</string>
		<key>com.apple.mobile.iTunes.accessories</key>
		<dict>
		</dict>
		<key>com.apple.mobile.wireless_lockdown</key>
		<dict>
		</dict>
		<key>UniqueDeviceID</key>
		<string>cb2f24e654d6d32223d9c96d9ee1115dca2a5b1e</string>
		<key>SerialNumber</key>
		<string>DMPR8D6MG5WQ</string>
		<key>DeviceName</key>
		<string>Suhail 's iPad</string>
	</dict>
	<key>SnapshotHMACKey</key>
	<data>
		+/3Lrnx9JoB2Rrz3GNa2wGM8iQU=
	</data>
</dict>
</plist>]}
13:38:30.248 [main] [1;31mERROR[0;39m c.g.h.i.data.backup.SnapshotFactory - -- from() - snapshot: Snapshot{snapshotID=S:BB695BF7-B209-4077-99F6-A10BA6B440C5, backupProperties=Optional[<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Version</key>
	<string>9.1</string>
	<key>Date</key>
	<date>2016-08-29T09:10:54Z</date>
	<key>SystemDomainsVersion</key>
	<string>24.0</string>
	<key>WasPasscodeSet</key>
	<false/>
	<key>AppleIDs</key>
	<dict>
		<key>tab@hasbroclothing.com</key>
		<dict>
		</dict>
		<key>prince18raj@gmail.com</key>
		<dict>
		</dict>
	</dict>
	<key>ActiveAppleID</key>
	<string>tab@hasbroclothing.com</string>
	<key>Lockdown</key>
	<dict>
		<key>com.apple.MobileDeviceCrashCopy</key>
		<dict>
		</dict>
		<key>com.apple.TerminalFlashr</key>
		<dict>
		</dict>
		<key>com.apple.mobile.data_sync</key>
		<dict>
			<key>Contacts</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Calendars</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Bookmarks</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
			<key>Notes</key>
			<dict>
				<key>AccountNames</key>
				<array>
					<string>iCloud</string>
				</array>
				<key>Sources</key>
				<array>
					<string>iCloud</string>
				</array>
			</dict>
		</dict>
		<key>com.apple.Accessibility</key>
		<dict>
			<key>SpeakAutoCorrectionsEnabledByiTunes</key>
			<false/>
			<key>ZoomTouchEnabledByiTunes</key>
			<false/>
			<key>InvertDisplayEnabledByiTunes</key>
			<false/>
			<key>ClosedCaptioningEnabledByiTunes</key>
			<false/>
			<key>MonoAudioEnabledByiTunes</key>
			<false/>
			<key>VoiceOverTouchEnabledByiTunes</key>
			<false/>
		</dict>
		<key>ProductVersion</key>
		<string>9.3.4</string>
		<key>ProductType</key>
		<string>iPad5,4</string>
		<key>BuildVersion</key>
		<string>13G35</string>
		<key>com.apple.mobile.iTunes.accessories</key>
		<dict>
		</dict>
		<key>com.apple.mobile.wireless_lockdown</key>
		<dict>
		</dict>
		<key>UniqueDeviceID</key>
		<string>cb2f24e654d6d32223d9c96d9ee1115dca2a5b1e</string>
		<key>SerialNumber</key>
		<string>DMPR8D6MG5WQ</string>
		<key>DeviceName</key>
		<string>Suhail 's iPad</string>
	</dict>
	<key>SnapshotHMACKey</key>
	<data>
		+/3Lrnx9JoB2Rrz3GNa2wGM8iQU=
	</data>
</dict>
</plist>]}



 B: DEVICE 2F462588122B04D7B3681D1BA38B7A728301AB0B iPad5,4 J82AP
 1:	 136 MB Suhail 's iPad (iOS 9.1)  2016-08-24T07:15:20.353Z
 2:	  39 MB Suhail 's iPad (iOS 9.1)  2016-08-27T07:21:18.349Z
 3:	  36 MB Suhail 's iPad (iOS 9.1)  2016-08-29T09:10:54.746Z
```

Each snapshot has different UDID.

Let me know you thoughts,
Thanks

**Comment by horrorho** [comment]
Thank you. I've edited your reply to remove superfluous details. The obvious common ground is the device model/ name that you can tie together. The formatting is slightly different but should be a trivial issue to fix.

I'm not sure how the api.device id is derived. It's a 384-bit byte sequence. Is it random or a hash derived value that ties in a physical device with an iCloud account? I don't have the time to research or play with it in detail.

Also backup device ids are not the same as a hardware unique device identifiers. A phone may have numerous backups with different backup device ids. A backup may be restored on to different devices each with their own unique device identifier.

> Each snapshot has different UDID.

The data you've pasted above has one backup with the id `2F462588122B04D7B3681D1BA38B7A728301AB0B`. It has three snapshots. There is no snapshot UDID. There is a backup that has been edited out (prior to my editing). It's difficult for me to comment on data that I cannot see. Are you seeing two backups for the same device?

If you can clarify exactly how you would like to co-relate InflatableDonkey/ PyiCloud I might be able to offer suggestions. If you were looking for a single backup for a particular device, it doesn't work like that. You may have none, one or many backups for a device.

**Comment by horrorho** [comment]
Closing ticket. No further input received.

**Comment by dinak1989** [comment]
Hi
We need UniqueDeviceId and its any way to get UniqueDeviceId from the below response:

<plist version="1.0">
    <dict>
        <key>Version</key>
        <string>9.1</string>
        <key>Date</key>
        <date>2017-03-11T12:17:34Z</date>
        <key>SystemDomainsVersion</key>
        <string>24.0</string>
        <key>WasPasscodeSet</key>
        <false/>
        <key>AppleIDs</key>
        <dict>
            <key>john.poul02@gmail.com</key>
            <dict>
            </dict>
            <key>vjsha699@gmail.com</key>
            <dict>
            </dict>
            <key>prince18raj@gmail.com</key>
            <dict>
            </dict>
            <key>prince18raj@rediffmail.com</key>
            <dict>
            </dict>
        </dict>
        <key>ActiveAppleID</key>
        <string>vjsha699@gmail.com</string>
        <key>Lockdown</key>
        <dict>
            <key>com.apple.MobileDeviceCrashCopy</key>
            <dict>
            </dict>
            <key>com.apple.TerminalFlashr</key>
            <dict>
            </dict>
            <key>com.apple.mobile.data_sync</key>
            <dict>
                <key>Contacts</key>
                <dict>
                    <key>AccountNames</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                    <key>Sources</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                </dict>
                <key>Calendars</key>
                <dict>
                    <key>AccountNames</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                    <key>Sources</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                </dict>
                <key>Bookmarks</key>
                <dict>
                    <key>AccountNames</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                    <key>Sources</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                </dict>
                <key>Notes</key>
                <dict>
                    <key>AccountNames</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                    <key>Sources</key>
                    <array>
                        <string>iCloud</string>
                    </array>
                </dict>
            </dict>
            <key>com.apple.Accessibility</key>
            <dict>
                <key>SpeakAutoCorrectionsEnabledByiTunes</key>
                <false/>
                <key>ZoomTouchEnabledByiTunes</key>
                <false/>
                <key>InvertDisplayEnabledByiTunes</key>
                <false/>
                <key>ClosedCaptioningEnabledByiTunes</key>
                <false/>
                <key>MonoAudioEnabledByiTunes</key>
                <false/>
                <key>VoiceOverTouchEnabledByiTunes</key>
                <false/>
            </dict>
            <key>ProductVersion</key>
            <string>10.2.1</string>
            <key>ProductType</key>
            <string>iPhone7,2</string>
            <key>BuildVersion</key>
            <string>14D27</string>
            <key>com.apple.mobile.iTunes.accessories</key>
            <dict>
            </dict>
            <key>com.apple.mobile.wireless_lockdown</key>
            <dict>
            </dict>
            <key>UniqueDeviceID</key>
            <string>b66fed086e04448241bc2503db81a313efcee433</string>
            <key>SerialNumber</key>
            <string>DNPNT5HKG5MD</string>
            <key>DeviceName</key>
            <string>Mobileteam</string>
        </dict>
        <key>SnapshotHMACKey</key>
        <data>
		snjdF2jheD8g3DxCsI+LOhUG14c=
	</data>
        <key>DisabledDomains</key>
        <array>
        </array>
    </dict>
</plist>]}

**Comment by horrorho** [comment]
@dinak1989 Hi. I need you to clarify your question please. Where do you want to get the corresponding UniqueDeviceId from? Your phone or from [pyicloud](https://github.com/picklepete/pyicloud)?

**Comment by dinak1989** [comment]
@horrorho 
Hi,Its not related to pyicloud using this line "logger.error("-- from() - snapshot: {}", snapshot);" i can able to see UniqueDeviceId and i need to retrieve it.

**Comment by horrorho** [comment]
@dinak1989 It's not standard functionality but you can code it in.

UniqueDeviceId exists with the Snapshot class within backupProperties which is an [NSDictionary](https://github.com/3breadt/dd-plist/blob/master/src/main/java/com/dd/plist/NSDictionary.java).
