### ISSUE TITLE
is it possible to work from the local (iTunes) backup folder?

### ISSUE THREAD

**Issue by avs099** [horrorho/InflatableDonkey#51]
Hello:

First of all - thank you for your great work! I used this app to extract data i needed from my phone - but before I could do that I had to go through the hassle of backing up my phone to iCloud - as I never used it before. I'm planning to do this for another phone of mine - and if I could just modify your app to point to local folder instead, that would be useful.

I'm not a Java guy - but I assume you have something like the following pseudo-code:

downloadiCloudBackup(string userName, string password, string tempFolder);
processBackup(string tempFolder);

if that's the case - can you please point me to corresponding module - so I can update the logic to skip downloading and instead use local backup folder? or am I totally mistaken and these things are not compatible at all?..

Thanks again.

**Comment by horrorho** [comment]
Hi there. It's probably not that straight forward. I've only looked briefly at the iTunes backup format and it doesn't match the data that we get from iCloud servers. As it is, iCloud data chunks/ asset data are forwarded to the FileAssembler which writes out files. This wouldn't work with iTunes backup data without modification.

You would need to implement a new FileAssembler/ support classes that recognises the iTunes backup format. Some existing classes may also need modification such at the key bag handlers. If you're a Python guy and not a Java guy, it's possible you might have an easier time hacking [iLoot](https://github.com/hackappcom/iloot) to get this done.

**Comment by horrorho** [comment]
No further discussion, closing issue.
