### ISSUE TITLE
Retrieve mmeAuthToken from backup

### ISSUE THREAD

**Issue by Aliasr** [horrorho/InflatableDonkey#53]
I know the mmeAuthToken can be retrieved during the authentication process, but is it possible to retrieve it afterwards from an already downloaded backup?

**Comment by horrorho** [comment]
Hi. As far as I'm aware the token is not present in the backup itself. It's possible you could apply forensic techniques and derive a password list which may assist you. There are options however to retrieve tokens from physical devices such as [MMeTokenDecrypt](https://github.com/manwhoami/MMeTokenDecrypt)

**Comment by Aliasr** [comment]
Hi @horrorho. Thanks for the quick response! [MMeTokenDecrypt](https://github.com/manwhoami/MMeTokenDecrypt) seems like a great tool, but unfortunately is not what I need. 

Do you have any idea where to start or which forensic techniques or files would be useful to create the password list? Also how could I try those tokens in the list?

**Comment by horrorho** [comment]
Hi, it would be simpler to find a suitable forum to discuss that in. InflatableDonkey is primarily a backup retrieval tool. I've tried to avoid getting drawn into too much in the way of data analysis/ forensics.

**Comment by Aliasr** [comment]
Alright, thanks!
