### ISSUE TITLE
IOs Version Issue 

### ISSUE THREAD

**Issue by prateek1108** [horrorho/InflatableDonkey#57]
Hello,

i am using inflatabledonkey code to download ios backups its working fine for till ios 10.3 but iam facing a issue .i tried to downlaod backups of 9.x and 10.x but the code shows IOs version as 9.1 for all the backups.How i can get the correct backup ios version.

**Comment by horrorho** [comment]
Hi and thank you. There various points that we can extract this information. There is another point we can use. I'll add it to the to do list. However there is another iOS project that I'm working on that is taking priority and I have limited time sadly, so a fix may be delayed.

**Comment by Jirmi** [comment]
Hi @horrorho, to fix this issue we can just replace code on line 99 in Snapshot.java with something similar to the following pseudo code:  backupProperties['Lockdown']['ProductVersion'].

**Comment by horrorho** [comment]
@Jirmi Hi. Thank you. That was the point I was considering but it's nice to have some additional confirmation.

**Comment by prateek1108** [comment]
hi...

Can by this code can we download backups whose version is less than ios 9. i.e ios 8 backups can we download.,?

**Comment by horrorho** [comment]
@prateek1108 Please use [iLoot](https://github.com/hackappcom/iloot) or [LiquidDonkey](https://github.com/horrorho/LiquidDonkey) for iOS8.

**Comment by prateek1108** [comment]
hello,

All working fine in icloud thanks for your guidance a great job is done.
I want to decrypt the encrypted backup of iphone 10.3 .what's the command or how i can do this and i didn't find any command to do so.

**Comment by horrorho** [comment]
@prateek1108 That is outside the remit of this project. You'll need to hunt down the appropriate tool/s.

**Comment by horrorho** [comment]
Issue patched.
