### ISSUE TITLE
ios9.3+ iCloud download failed

### ISSUE THREAD

**Issue by pallassgj** [horrorho/InflatableDonkey#6]
I tried to use the Java and found a serious problem. The reason to fail to detect iCloud backup within iOS 9.3+ and higher is that the length of protectionInfo.getProtectionInfo(located in protectionInfo) is discordant with ASN1. The length of wrong files is always 59 bytes，but the length of analysis is larger than this. Thus, it causes parse()(located in DERUtils) displaying abnormally. I fail to analysis it. BTW, I find almost all iOS 9.3+ devices encounter this problem while downloading backups. I hope someone can give me some suggestions

**Comment by valenokk** [comment]
Hi, I'm not sure if it's somehow connected, but did you check this thread?
https://github.com/hackappcom/iloot/issues/62#issuecomment-213391984

**Comment by prateek1108** [comment]
hi,
i had tried this code a great work is done the code is downloading files upto 9.2.1 version. 
Few things issues or error are coming while downloading ios backups
1) is this code download all the version files below 9.2.1(backups of 8.x ).
2 )Is any progress is there for 9.3 and above ios version.

**Comment by horrorho** [comment]
Sorry the delay! I've pushed a new build that you may like to test.

**Comment by prateek1108** [comment]
i appreciate the work you had done.....i had checked for 9.0 and above code is working.

**Comment by horrorho** [comment]
Thank you. I'll close the ticket.
