### ISSUE TITLE
Porting to Android

### ISSUE THREAD

**Issue by oct-test** [horrorho/InflatableDonkey#64]
Hello,

I am planning to port this tool to Android. However, the tool is written in Java 8 and Android SDK does not support all the Java 8 features.

I am looking for some help if some one ported this tool in other languages such as Python or Java 7.

Thank you.

**Comment by horrorho** [comment]
Hi. I'm not aware of any open source ports. In addition to the Java 8 issues you'll also need to check that the libraries the project uses are available to you.

**Comment by oct-test** [comment]
For downloading the file chunks from the iCloud server, I am receiving different chunk encryption key in my code compared to your tool. What can be the possible reasons for this difference in the chunk encryption keys?

**Comment by horrorho** [comment]
@oct-test Hi. I assume that your code is not working as intended. Without the benefit of additional information, I suspect it may be due to a mix up over type 1/ 2 chunk encryption keys. My comment [here](https://github.com/horrorho/InflatableDonkey/issues/38#issuecomment-260858169) might clarify the situation.

**Comment by oct-test** [comment]
@horrorho Thank you for the help.

**Comment by oct-test** [comment]
@horrorho Is it possible to optimize the CloudKit.java file as the Android system has limitation of 64K method references in a single .dex file?

**Comment by horrorho** [comment]
@oct-test [CloudKit.java](https://github.com/horrorho/InflatableDonkey/blob/master/src/main/java/com/github/horrorho/inflatabledonkey/protobuf/CloudKit.java) is generated using Google's [Protocol Buffers](https://github.com/google/protobuf) protoc tool. The raw proto file is [cloud_kit.proto](https://github.com/horrorho/InflatableDonkey/blob/master/src/main/resources/cloud_kit.proto). As discussed [here](https://stackoverflow.com/questions/15436956/how-to-solve-the-issue-with-dalvik-compiler-limitation-on-64k-methods) on StackOverflow, it appears others have also had similar issues with the unwieldy protoc generated classes and some solutions are offered.

**Comment by oct-test** [comment]
@horrorho Congratulations for making InflatableDonkey compatible with iOS 11. I read some of your other discussion about LZFSE. Are there any LZFSE implementations for Java? I possibly wanted to port it to Android.

**Comment by horrorho** [comment]
Hi in light of recent [occurrences](https://github.com/horrorho/InflatableDonkey/issues/56#issuecomment-312075165) I'm no longer offering support for developers creating their own tools/ services. If you would like to open up your project to the open source community I will assist. In the meantime please use the resources available to you to find a solution.
