### ISSUE TITLE
No backups

### ISSUE THREAD

**Issue by ciucaandrei** [horrorho/InflatableDonkey#7]
Hi,

I have tested with 2 devices. On both devices I can validate the email/password. I also get the name for the icloud account. But for both devices, I get the message that there are no backups

The first device is on ios 9.0.2 - I think it is possible that this script only works on 9.2
The second device is on ios 9.3.2 - for this it should not work from what others have reported.

**Comment by horrorho** [comment]
Sorry for the delay! I've pushed a new build that you may like to try. Please advice if the issue persists.

**Comment by horrorho** [comment]
Closing the ticket as I've not heard anything. Please re-open if the issue persists with the newer builds.

**Comment by ciucaandrei** [comment]
I can confirm that it works for 9.0.2 and 9.3.2
Really amazing work

**Comment by horrorho** [comment]
Thank you for the feedback!
