### ISSUE TITLE
[Help] Sorry if I'm just being really dumb, but I keep getting "compilation failure"

### ISSUE THREAD

**Issue by gamingbro** [horrorho/InflatableDonkey#71]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project InflatableDonkey: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[ERROR]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project InflatableDonkey: Compilation failure
No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
```

This is what I get after I just tried "mvn clean install -X" as I hoped that would perhaps fix my problem. I have not gotten this program to work yet, so I'm doing something wrong. Any idea on what I need to do to fix it? I can provide more information if needed. Thanks!

**Comment by horrorho** [comment]
Heya. Not a dumb question. I suspect your Java JDK installation is at fault.

Mkyong has some accessible guides on Java/ Maven installation: [Windows](https://www.mkyong.com/maven/how-to-install-maven-in-windows/) / [macOS](https://www.mkyong.com/maven/install-maven-on-mac-osx/). I would suggest working through those and confirming that you can complete the verification step.

If you have no luck would you kindly let me know the output of the following commands:
```
mvn --version
```
```
java -version
```
```
javac -version
```

**Comment by gamingbro** [comment]
I must be doing something wrong, but I can't figure out where I'm messing up. These are the errors I'm getting for up above.

```
C:\WINDOWS\system32>mvn --version
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

C:\WINDOWS\system32>java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

C:\WINDOWS\system32>javac -version
'javac' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>
```

Perhaps I'm supposed to "cd" to a different location?
