### ISSUE TITLE
Files with '?' crashes InflatableDonkey  java.nio.file.InvalidPathException:

### ISSUE THREAD

**Issue by gizmo345** [horrorho/InflatableDonkey#8]
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <?> at index 22: Documents/WHERE_YOU_AT?!

**Comment by horrorho** [comment]
Thank you for the ticket.

I've pushed a new build that should resolve the issue. I had neglected to escape illegal file path characters for Windows environments.

Please let me know if the issue persists or if you are using a non Windows environment.

**Comment by horrorho** [comment]
Closing the ticket, please re-open if  the issue persists despite the code fixes. Thank you.
