### ISSUE TITLE
Project abandoned

### ISSUE THREAD

**Issue by JonasOlson** [horrorho/InflatableDonkey#80]
> **IMPORTANT NOTICE**, 6 November 2017.
>
> Without being able to expand on the reasons why and with immediate effect, I will no longer be maintaining this project or servicing tickets. I'm also unable to divulge any information regarding iOS/ iCloud mechanics or render any assistance in this regard.
>
> I apologise for this.

Your language is clear. We hear what you're trying to say. I'm sorry that this happened. Thank you for helping me access my backups!

**Comment by Yaldo425** [comment]
It's sad to hear that the tool has been discontinued. Thank you horrorho for all of your hard work! There is no doubt that maintaining InflatableDonkey was difficult and time-consuming.

InflatableDonkey is currently the only free program that can acquire backups and remains the only program that doesn't lock apple IDs ( #56 )

**Comment by xrolabs** [comment]
> There is no doubt that maintaining InflatableDonkey was difficult and time-consuming.

@Yaldo425 I don't think that's the reason. @horrorho was working on an advanced iCloud tool for the best part of a year. It's an open secret that she had figured out how to circumnavigate things like 2FA.

> Without being able to expand on the reasons why and with immediate effect, I will no longer be maintaining this project or servicing tickets. I'm also unable to divulge any information regarding iOS/ iCloud mechanics or render any assistance in this regard.

Reading between the lines of her statement, it sounds very much like either:

- she was head hunted and bought out, everyone has their price.

- Apple found out and came down on her like a ton of bricks.

Either way an NDA would be involved hence her being unable to expand on the reasons why.

For what it's worth I suspect she was bought out. She mentioned that her private tool would not become public. If this is the case then why put in all that effort to create something that has no consumer?

I don't mean this as a criticism but she has been known to be evasive. InflatableDonkey has always been able to download iPhotos and Photo Streams. She never released these updates to the public as she did not want to cater to the 'creeps' out there although she never commented as such, instead deferring to excuses about lack of time or other.

I've tried contacting her but she's no longer replying to my emails. Maybe others will have better luck establishing the facts.

@horrorho Please don't take any of this to heart if you do read this. I'm a great fan of your work and I've forever been in awe of your skill. However I think the community deserves an answer that understandably you're unable to provide. Peace out.
