### ISSUE TITLE
Anyone looking for a ready made iOS 12 2FA solution ..?

### ISSUE THREAD

**Issue by Poseidone** [horrorho/InflatableDonkey#89]
please message me

**Comment by dirkwirth** [comment]
Hey i am looking for this solution.
Please can you send me message in dirk.wirth6@gmail.com?
Thank you

**Comment by netsutra** [comment]
Hi Poseidone, I would be interested. Please email me sanjay.jindal@netsutra.com

**Comment by wholeeoh** [comment]
Poseidone, I'm intrerested as well. stylen@gmail.com

**Comment by codebar33** [comment]
Who is the magic Poseidon? :)

**Comment by liwenjie0728** [comment]
Hi Poseidone, I am interested. Please email me stevenlee6668@gmail.com

**Comment by oct-test** [comment]
Hi, I am interested. Please email me to octanetest123@gmail.com. Thank you.

**Comment by Monst3r1999** [comment]
Hey Mate, Im interested as well.  tonystark2020@protonmail.com

**Comment by preetisantoki** [comment]
Hey Mate, I'm interested as well. 
Please mail me to p.santoki88@gmail.com
Thank you.

**Comment by horrorho** [comment]
Complaint received. I've not investigated any further, so honestly I have no idea if this is genuine or not. 

However this repository is not an advertising board and I don't have time to settle disputes that are outside the scope of this project.

Locked and closed. Sorry.
