### ISSUE TITLE
unreadable media files

### ISSUE THREAD

**Issue by kokozaurz** [horrorho/InflatableDonkey#9]
Hi,

first of all - thanks for developing this tool and keeping it up to date. 

The issue is as follows: 

From device labeled as "iPhone8,1 N71AP" the downloaded media files (images/video) are not readable if they are in **whatsapp/messenger** or pretty much any other directory other than camera roll. Camera roll stuff is completely fine. 

Also on a side note, it would be much easier if it would be possible to at least have an option for all the whatsapp files to be dropped just in 'whatsapp' directory similar to camera roll rather than building the whole whatsapp directory tree which makes it way harder to access files. I understand that it probably pulls that way from the server but would it be possible that it just saves all files in main directory so you don't have to go through trees of directories to see the files?

Thanks!

**Comment by horrorho** [comment]
Thank you for your feedback.

I'm aware of the broken file issue with certain domains and I have been working on it. I reversed the file checksum algorithms earlier today and I'm half way through coding them. This should tell us if our file decryption is faulty or if applications are using their own additional encryption. If it's the latter then it's currently outside the scope of this project.

I'll report back once I have more information.

As for the the WhatsApp file issue, it's a trivial matter to find, cut/ copy and paste them into a single folder using Windows Explorer search box. It's just as simple on most Linux distros. There's no need to work through individual folders.

**Comment by horrorho** [comment]
Ok, it's a decryption issue which I'll need to look into. Certain protection classes are not being decrypted properly.

**Comment by kokozaurz** [comment]
Thanks. I'm on OS X - what practice would you recommend to move the files?

**Comment by horrorho** [comment]
I don't have any OSX or iOS devices, so I'll leave it up to others to suggest the best approach.

Either way the core of this concept tool is to retrieve backups, not to manipulate backups post retrieval.

**Comment by horrorho** [comment]
Ok! I spent all night on this and I've pushed a new build. My current retrieval has no WhatsApp file corruption issues whereas it did on previous builds.

As for the cause, I managed to break the protection class key bag/ file decryption code somehow. Obviously I have no idea what I'm doing at times.

If you would kindly try out the new build and let me know if the issues persists. Thank you.

**Comment by kokozaurz** [comment]
@horrorho just tried it, still unreadable. can upload a random unreadable file from the bunch if that helps?

**Comment by horrorho** [comment]
Which iOS version are you using? 
Are you able to view files in the media or other domains?

I don't think the random files will help. There is another checksum that I've not reversed yet, which should give us a post protection class decryption status. I'll try and work on that as it may give us additional clues.

I may have imagined it, but I vaguely remember newer versions of WhatsApp using disk encryption hence why I'm interested to know if you can view files in other domains.

**Comment by kokozaurz** [comment]
Yes I can. In addition to the one mentioned above I also have iPhone6,2 N53AP. It decrypts all files correctly and **everything** is viewable.

iOS is 9.3

Theoretically speaking (i'm no crypto expert), wouldn't the encrypted file help to test out various decryption methods locally?

**Comment by horrorho** [comment]
Unfortunately no. Without the decryption key it will appear as random data. To brute force the key would take time magnitudes longer than the  age of the universe.

Though I suspect it's an additional security layer that WhatsApp have introduced I will endeavour to reverse the aforementioned other checksum. I have a checksum for data prior to protection class decryption, but not for data post decryption. There is still the chance that the decryption algorithms are buggy.

Again thank you for the feedback. I'll continue to work on this issue.

**Comment by colincowie10** [comment]
Hi,
 Great work! I too (iOS 9.3) can not open any media files excluding CameraRollDomain. Currently on the newest build.

Thank you for all your hard work.

**Comment by horrorho** [comment]
@colincowie10 Thank for the feedback. It appears that the protection class decryption has issues with certain backups. The reason for this is unclear to me at the moment but I am looking into it as a priority.

**Comment by colincowie10** [comment]
Thank you!

**Comment by colincowie10** [comment]
Gotcha, keep up the hard work! Much appreciated.

**Comment by horrorho** [comment]
Ok. I've figured it out, well mostly. It's an issue with XTS-AES encryption that is tied to the type of device used to create the backup, not to iOS 9.3 per se. I'm currently finishing off XTS-AES code and I'll start testing over the next day or two. I still need to figure out the detection routines for when to use the conventional AES-CBC decryption or the XTS decryption.

**Comment by t3zuka** [comment]
Would you mind pushing a new branch with the changes so far if you get chance, I'd like to see how it fits together.

**Comment by horrorho** [comment]
Sorry for the wait! I've pushed the new code. Please refer to the [main page](https://github.com/horrorho/InflatableDonkey) for caveats.
