### ISSUE TITLE
New Patch not working , not able to download backup

### ISSUE THREAD

**Issue by preetisantoki** [horrorho/InflatableDonkey#93]
Hi @horrorho  Thanks for your last patch, but that seem to be working for some time only. Currenty we are not able to download the backup of icloud.

We know like you have less time and this project is now we all need to run ourselves. We are trying but need some time and meanwhile, we request you to kindly update any new patch if needed.

Current issue: once we select specific backup to download it automatically terminate the session.

**Comment by horrorho** [comment]
Hi. Kindly refer to #87
